#pragma once

#define GEM_MOUSE_BUTTON_1         0
#define GEM_MOUSE_BUTTON_2         1
#define GEM_MOUSE_BUTTON_3         2
#define GEM_MOUSE_BUTTON_4         3
#define GEM_MOUSE_BUTTON_5         4
#define GEM_MOUSE_BUTTON_6         5
#define GEM_MOUSE_BUTTON_7         6
#define GEM_MOUSE_BUTTON_8         7
#define GEM_MOUSE_BUTTON_LAST      GEM_MOUSE_BUTTON_8
#define GEM_MOUSE_BUTTON_LEFT      GEM_MOUSE_BUTTON_1
#define GEM_MOUSE_BUTTON_RIGHT     GEM_MOUSE_BUTTON_2
#define GEM_MOUSE_BUTTON_MIDDLE    GEM_MOUSE_BUTTON_3